-- Crear tabla usuarios
CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    fecha_registro TIMESTAMP NOT NULL,
    activo BOOLEAN DEFAULT TRUE
);

-- Quitar la columna anterior 'autor'
ALTER TABLE topicos DROP COLUMN autor;

-- Agregar columna nueva como FK
ALTER TABLE topicos ADD COLUMN usuario_id BIGINT NOT NULL;

-- Clave foránea hacia usuarios
ALTER TABLE topicos
ADD CONSTRAINT fk_topicos_usuario
FOREIGN KEY (usuario_id)
REFERENCES usuarios(id);
