CREATE TABLE cursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(100) NOT NULL,
    categoria VARCHAR(100) NOT NULL
);

-- Eliminar columna cursos de tabla topicos
ALTER TABLE topicos DROP COLUMN curso;

-- Agregar nueva columna cursos en tabla topicos
ALTER TABLE topicos ADD COLUMN curso_id BIGINT NOT NULL;

-- Crear relación
ALTER TABLE topicos
ADD CONSTRAINT fk_topico_curso
FOREIGN KEY (curso_id)
REFERENCES cursos(id);
