CREATE TABLE respuestas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topico_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    mensaje TEXT NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    ultima_modificacion TIMESTAMP NOT NULL,
    solucion BOOLEAN NOT NULL DEFAULT FALSE,
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_respuesta_topico FOREIGN KEY (topico_id) REFERENCES topicos(id),
    CONSTRAINT fk_respuesta_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);